# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nqdBOKPDEKYnpE6gXHgqAXIBYIOAJB9t
"""

import pandas as pd
import numpy as np
import streamlit as st
import joblib


import pickle
# Save model to file
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)
st.title("Predicted selling_price")

# UI inputs
owner= st.number_input("owner")
yr_old = st.number_input("yeard_old")
km_dri = st.number_input("km_driven")
mil_val = st.number_input("mileage_value")

# Predict
if st.button("Predict"):
    prediction = model.predict(
        [[owner, yr_old, km_dri, mil_val]]
    )
    st.success(f"Predicted selling_price: ${prediction[0]:.2f}")